on: [push, pull_request]

jobs:

  test:
    name: "Test Rust"
    runs-on: ubuntu-latest
    defaults: 
      working-directory: percolation-rust

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: cargo test
      - run: wasm-pack test --headless --chrome
      - run: wasm-pack test --headless --firefox
